### ISSUE TITLE
Workspace API need to contain space color entry

### ISSUE THREAD

**Issue by quan0715** [quan0715/grouping_application#47]
I found that the responses of the workspace api do not have any field to represent space color, while I need this attribute to render the whole page theme in each space. 

Additionally, I think user space color might also be added in user data. I don't know is it be proper operation to add color field directly in user data table?

**Comment by quan0715** [comment]
For example from Figma the color different from each workspace.
![image](https://github.com/quan0715/grouping_application/assets/60366187/ded715e2-3bd7-412c-8191-8cfd084698cf)
![image](https://github.com/quan0715/grouping_application/assets/60366187/c2aacc62-2cc2-4eb7-92bb-db8df368ebfc)

**Comment by Bryant-Tang** [comment]
the workspace is already have a field called "theme_color", which store an integer. Is it what you called space color?
And as for the color in user data, in the team meeting long ago, we have discussed about this, and the result is that since the personal workspace have a color field, and it should also represent the user color, the user data do not need another color field.
